# Generated by Django 5.1.5 on 2026-06-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="verification_source",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="verified_skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
