# Generated by Django 5.1.5 on 2026-06-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("saved", "Saved"),
                    ("applied", "Applied"),
                    ("interview", "Interviewing"),
                    ("offer", "Offer"),
                    ("hired", "Hired"),
                    ("rejected", "Rejected"),
                    ("ghosted", "Ghosted"),
                ],
                default="saved",
                max_length=20,
            ),
        ),
    ]
