# Generated by Django 5.1.5 on 2026-06-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="edited_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="fixes",
            field=models.JSONField(default=list),
        ),
    ]
